// 24 Courses Data for Al-Itqan Institute
const courses = [
  // Quran Courses (7)
  {
    title: 'Noorani Qaida Course',
    category: 'Quran',
    level: 'Beginner',
    duration: '2-3 Months',
    fee_usd: '$20-$30',
    fee_pkr: '~PKR 5,500-8,500',
    prerequisites: 'None',
    description: 'A beginner-level course designed for students who want to start learning how to read the Holy Quran correctly. Focuses on basic Arabic alphabet, correct pronunciation (Makharij), joining letters, and simple reading rules. Suitable for children, beginners, and new learners with no prior Arabic knowledge. Students learn to recognize Arabic letters, pronounce from correct articulation points, combine letters into words, and read short Quranic phrases accurately.',
    learning_outcomes: 'Identify all Arabic letters · Read joined letters and words · Apply basic pronunciation rules · Prepare for Quran Reading with Tajweed',
    schedule: '3-5 days/week · 30 min (children) / 45 min (adults)',
    sort_order: 1
  },
  {
    title: 'Nazra Quran (Quran Reading Course)',
    category: 'Quran',
    level: 'Beginner',
    duration: '3-4 Months',
    fee_usd: '$25-$35',
    fee_pkr: '~PKR 7,000-10,000',
    prerequisites: 'Noorani Qaida or basic Arabic letters knowledge',
    description: 'Designed for students who know basic Arabic letters and want to read the Holy Quran fluently and correctly. Focuses on reading speed, accuracy, and confidence while applying basic Tajweed rules. Regular recitation practice, listening exercises, and correction sessions develop proper Quran reading skills.',
    learning_outcomes: 'Read the Holy Quran confidently · Recognize common Tajweed rules · Prepare for advanced Tajweed learning',
    schedule: '3-5 days/week · 30 min (children) / 45 min (adults)',
    sort_order: 2
  },
  {
    title: 'Quran with Tajweed Course',
    category: 'Quran',
    level: 'Intermediate',
    duration: '4-6 Months',
    fee_usd: '$30-$40',
    fee_pkr: '~PKR 8,500-11,500',
    prerequisites: 'Nazra Quran or ability to read the Quran',
    description: 'Advanced Quran recitation course for students who can read the Quran but want to perfect recitation by mastering complete Tajweed rules — Makharij, Sifaat, Ikhfa, Idgham, Iqlab, Qalqalah, Madd rules, and Waqf/Ibtida. Teachers guide step-by-step through Quranic verse recitation with live correction.',
    learning_outcomes: 'Recite the Holy Quran clearly, confidently, and according to proper Tajweed rules',
    schedule: '3-5 days/week · 30 min (children) / 45 min (adults)',
    sort_order: 3
  },
  {
    title: 'Advanced Tajweed Program',
    category: 'Quran',
    level: 'Advanced',
    duration: '1 Year',
    fee_usd: '$35-$50',
    fee_pkr: '~PKR 10,000-14,000',
    prerequisites: 'Quran with Tajweed Course',
    description: 'Complete one-year advanced Tajweed training program covering both theoretical and practical Tajweed. Topics include Makharij, Sifaat, Noon Saakinah/Meem Saakinah rules, Ikhfa, Idgham, Iqlab, Qalqalah, Madd rules, Waqf/Ibtida, and advanced recitation techniques. Students study from classical and recognized Tajweed books under qualified teacher supervision.',
    learning_outcomes: 'Develop strong theoretical Tajweed knowledge · Recite the Holy Quran fluently and accurately according to authentic Tajweed rules · Prepare for high-level Quran recitation and further Islamic studies',
    main_books: 'Jamal ul-Quran, Khulasat ut-Tajweed, Fawaid Makkiyah, Al-Jazariyyah (Ibn al-Jazari)',
    schedule: '3-5 days/week · 30-45 min per session',
    sort_order: 4
  },
  {
    title: 'Hifz-ul-Quran (Quran Memorization Program)',
    category: 'Quran',
    level: 'Specialized',
    duration: '2.5-3 Years (Complete Hifz) / 6 Months-1 Year (Partial)',
    fee_usd: '$40-$60',
    fee_pkr: '~PKR 11,000-17,000',
    prerequisites: 'Ability to read Quran correctly with Tajweed',
    description: 'Specialized memorization course for students wishing to memorize the Holy Quran completely or partially under qualified Huffaz supervision. Focuses on systematic memorization, daily revision (Muraja\'ah), and correct recitation with Tajweed. Students follow a structured daily routine of new lesson (Sabaq), recent revision (Sabaqi), and old revision (Manzil) to strengthen memorization and maintain accuracy.',
    learning_outcomes: 'Complete or partial Quran memorization with Tajweed · Lifelong retention through structured revision methodology',
    schedule: '5 days/week · 45-60 min per session',
    sort_order: 5
  },
  {
    title: 'Tarjamat-ul-Quran Course',
    category: 'Quran',
    level: 'Intermediate',
    duration: '1 Year',
    fee_usd: '$30-$45',
    fee_pkr: '~PKR 8,500-12,000',
    prerequisites: 'Basic Quran reading or Tajweed completion',
    description: 'Comprehensive program for students wanting to understand the meanings and translation of the Holy Quran. Focuses on Quranic verse interpretation, translation (Tafsir in simple language), key themes, moral guidance, rules, and lessons. Connects the Arabic text with meaning through lectures, interactive discussions, verse-by-verse explanation, and real-life application examples.',
    learning_outcomes: 'Read Quranic verses and understand their translation accurately · Explain lessons and guidance contained in the Quran · Prepare for advanced Islamic studies',
    schedule: '3-5 days/week · 45-60 min per session',
    sort_order: 6
  },
  {
    title: 'Advanced Tafseer-ul-Quran Course',
    category: 'Quran',
    level: 'Advanced',
    duration: '2 Years',
    fee_usd: '$40-$60',
    fee_pkr: '~PKR 11,000-17,000',
    prerequisites: 'Tarjamat-ul-Quran or equivalent',
    description: 'Specialized two-year program for deep understanding of the Holy Quran — meanings, context, and rulings. Goes beyond basic translation to comprehensive analysis including linguistic, grammatical, jurisprudential, and historical contexts. Covers Usul al-Tafseer, Ta\'wil and Tafsir, Asbab al-Nuzul, Ahkam al-Quran, Naskh (abrogation), and cross-referencing with Hadith and Sunnah.',
    learning_outcomes: 'Understand the Quran in depth · Explain complex verses · Derive rulings · Teach Tafseer to others · Prepare for higher Islamic scholarship',
    main_books: 'Tafseer Ibn Kathir, Tafseer Al-Jalalayn, Tafseer Al-Tabari',
    schedule: '3-5 days/week · 45-60 min per session',
    sort_order: 7
  },

  // Arabic Language Courses (4)
  {
    title: 'Beginner Arabic Course',
    category: 'Arabic',
    level: 'Beginner',
    duration: '3 Months',
    fee_usd: '$20-$30',
    fee_pkr: '~PKR 5,500-8,500',
    prerequisites: 'None',
    description: 'Designed for students with no prior Arabic knowledge. Builds a strong foundation in Arabic reading, writing, and comprehension covering the Arabic alphabet, pronunciation (Makharij), basic vocabulary, simple sentence structure, Quranic word recognition, and essential phrases for daily use. Uses interactive teaching methods including practice exercises, reading drills, and pronunciation correction.',
    learning_outcomes: 'Read Arabic words · Understand simple phrases · Write basic sentences · Recognize Quranic words for further studies',
    main_books: 'Al-Arabiyyah Bayna Yadayk, Arabic for Beginners',
    schedule: '3-5 days/week · 30-45 min per session',
    sort_order: 8
  },
  {
    title: 'Intermediate Arabic Course',
    category: 'Arabic',
    level: 'Intermediate',
    duration: '6 Months',
    fee_usd: '$25-$40',
    fee_pkr: '~PKR 7,000-11,000',
    prerequisites: 'Beginner Arabic Course or basic Arabic knowledge',
    description: 'Builds on beginner foundations with intermediate grammar (nouns, verbs, tenses, gender, sentence structure), expanded vocabulary, reading short paragraphs, writing simple sentences, and basic conversational skills. Includes reading exercises, conversation practice, writing short paragraphs, and comprehension drills. Also addresses Quranic phrase comprehension for practical Islamic learning.',
    learning_outcomes: 'Read and understand intermediate Arabic texts · Write simple paragraphs · Communicate in basic conversation · Prepare for Advanced Spoken Arabic',
    main_books: 'Al-Kitaab fii Ta\'allum al-\'Arabiyya (Parts 1 & 2), Arabic Grammar Made Easy',
    schedule: '3-5 days/week · 45-60 min per session',
    sort_order: 9
  },
  {
    title: 'Advanced Spoken Arabic Course',
    category: 'Arabic',
    level: 'Advanced',
    duration: '1 Year',
    fee_usd: '$35-$50',
    fee_pkr: '~PKR 10,000-14,000',
    prerequisites: 'Intermediate Arabic Course',
    description: 'For students who have completed Intermediate level and want to achieve fluency in Arabic speaking, reading, writing, and comprehension. Covers advanced grammar, complex sentence structures, advanced vocabulary for daily and Islamic contexts, fluent conversation, Quranic and Hadith Arabic comprehension, essay writing, and listening skills. Teaching methods include role-playing, conversation drills, listening comprehension, essay writing, Quranic text analysis, and interactive discussions.',
    learning_outcomes: 'Speak Arabic fluently · Understand classical and Quranic Arabic · Write advanced texts · Engage confidently in conversation · Prepare for higher Islamic studies or teaching Arabic',
    main_books: 'Al-Mawrid (Arabic-English Dictionary), Fus\'ha Arabic for Advanced Learners, Arabic Conversation Made Easy',
    schedule: '3-5 days/week · 45-60 min per session',
    sort_order: 10
  },
  {
    title: 'Advanced Ilm-e-Balaghat Course (Arabic Eloquence & Rhetoric)',
    category: 'Arabic',
    level: 'Advanced',
    duration: '1 Year',
    fee_usd: '$40-$60',
    fee_pkr: '~PKR 11,000-17,000',
    prerequisites: 'Advanced Arabic or equivalent',
    description: 'Designed for students wanting to master Arabic eloquence (Balagha), the art of rhetoric, literary analysis, and stylistic excellence. Covers Ilm al-Ma\'ani (Science of Meanings), Ilm al-Bayan (Science of Clarity — metaphors, similes, allegories, metonymy), and Ilm al-Badi\' (Science of Literary Ornamentation — figures of speech). Includes practical Quranic and Hadith analysis, classical Arabic poetry analysis, and stylistic writing exercises.',
    learning_outcomes: 'Analyze Quranic verses and Hadith using Balagha principles · Recognize and apply advanced rhetorical devices · Compose eloquent Arabic texts · Prepare for advanced Tafseer, Hadith analysis, and Arabic literature scholarship',
    main_books: 'Balaghat-ul-Quran, Al-Balagha al-Wadihah, Al-Bayan wa al-Tabyin (Al-Jahiz), Al-Badi\' fi al-Adab, Optional: Miftah al-Balagha',
    schedule: '3-5 days/week · 45-60 min per session',
    sort_order: 11
  },

  // Fiqh Courses (6)
  {
    title: 'Basic Fiqh Course',
    category: 'Fiqh',
    level: 'Beginner',
    duration: '2-3 Months',
    fee_usd: '$20-$30',
    fee_pkr: '~PKR 5,500-8,500',
    prerequisites: 'None',
    description: 'Introduces fundamentals of Islamic jurisprudence in a simple, accessible manner. Covers acts of worship (Ibadat) — Salah, Sawm, Zakat, Hajj — and personal/social conduct (Mu\'amalat) including cleanliness, eating etiquettes, and family interactions. Students learn to distinguish between Wajib, Mustahab, Mubah, Makruh, and Haram. Step-by-step lessons with interactive practice and exercises.',
    learning_outcomes: 'Recognize and apply basic fiqh rulings in worship and daily activities · Perform Salah, fasting, Zakat, and Hajj correctly · Build foundation for Intermediate Fiqh',
    main_books: 'Mukhtasar al-Qudoori',
    schedule: '3-5 days/week · 45 min per session',
    sort_order: 12
  },
  {
    title: 'Intermediate Fiqh Course',
    category: 'Fiqh',
    level: 'Intermediate',
    duration: '6 Months',
    fee_usd: '$25-$35',
    fee_pkr: '~PKR 7,000-10,000',
    prerequisites: 'Basic Fiqh (Qudoori)',
    description: 'Builds on basic Fiqh with more detailed rulings and practical applications. Advanced worship topics include missed/combined prayers, special fasting cases, detailed zakat calculation, and Hajj/Umrah rituals. Social and financial matters — marriage, divorce, inheritance basics, contracts, and business transactions — are studied in greater depth. Real-life examples and teacher-led discussions strengthen understanding.',
    learning_outcomes: 'Apply fiqh rulings to complex worship and social situations · Understand reasoning behind Islamic laws · Prepare for Advanced Fiqh and scholarly discussions',
    main_books: 'Kanz ud-Daqaiq',
    schedule: '3-4 days/week · 60 min per session',
    sort_order: 13
  },
  {
    title: 'Advanced Fiqh Course',
    category: 'Fiqh',
    level: 'Advanced',
    duration: '12 Months (1 Year)',
    fee_usd: '$35-$50',
    fee_pkr: '~PKR 10,000-15,000',
    prerequisites: 'Intermediate Fiqh (Kanz)',
    description: 'Designed for students seeking mastery in Islamic jurisprudence. Using the classical text Al-Hidaya, students explore in-depth rulings for all acts of worship, complex social dealings, inheritance, criminal laws, and contemporary challenges. Emphasizes research skills, analytical thinking, and the ability to apply fiqh principles to modern situations. Prepares students for scholarly work, teaching, or advanced fiqh research, including skills to issue informed rulings (Ifta).',
    learning_outcomes: 'Master classical fiqh texts · Apply Islamic law to contemporary scenarios · Conduct scholarly research · Issue informed fiqh guidance · Develop expertise for teaching or issuing fatawa',
    main_books: 'Al-Hidaya (Imam al-Marghinani)',
    schedule: '3-4 days/week · 60-90 min per session',
    sort_order: 14
  },
  {
    title: 'Basic Usool Fiqh Course',
    category: 'Fiqh',
    level: 'Beginner',
    duration: '3 Months',
    fee_usd: '$20-$30',
    fee_pkr: '~PKR 5,500-8,500',
    prerequisites: 'None',
    description: 'Designed for students new to the principles of Islamic jurisprudence. Using Usool Shashi, students learn foundational rules and terminology for deriving Islamic rulings from the Quran and Sunnah. Topics include primary Shariah sources (Quran, Sunnah, Ijma, Qiyas), basic types of evidence, and understanding obligatory, recommended, and permissible actions. A simple and practical approach to understanding how jurists make legal decisions.',
    learning_outcomes: 'Understand basic principles of Islamic law and legal derivation · Learn key fiqh terminology and concepts · Prepare for Intermediate Usool Fiqh',
    main_books: 'Usool Shashi',
    schedule: '3-5 days/week · 45 min per session',
    sort_order: 15
  },
  {
    title: 'Intermediate Usool Fiqh Course',
    category: 'Fiqh',
    level: 'Intermediate',
    duration: '6 Months',
    fee_usd: '$25-$35',
    fee_pkr: '~PKR 7,000-10,000',
    prerequisites: 'Basic Usool Fiqh (Shashi)',
    description: 'Builds on Shashi foundations using Noor-ul-Anwar to guide students through intermediate principles of Islamic jurisprudence — Ijtihad, Qiyas, Ijma, definitive vs. speculative texts, and masalih al-mursalah (public interest). Emphasizes applying principles to real-life fiqh cases and preparing students for advanced classical text study.',
    learning_outcomes: 'Apply Usool Fiqh principles up to Qiyas · Understand reasoning behind juristic differences · Analyze real-life fiqh issues using scholarly methodology',
    main_books: 'Noor-ul-Anwar (up to Qiyas)',
    schedule: '3-4 days/week · 60 min per session',
    sort_order: 16
  },
  {
    title: 'Advanced Usool Fiqh Course',
    category: 'Fiqh',
    level: 'Advanced',
    duration: '12 Months (1 Year)',
    fee_usd: '$35-$50',
    fee_pkr: '~PKR 10,000-15,000',
    prerequisites: 'Intermediate Usool Fiqh',
    description: 'For students aiming to achieve mastery in Islamic legal theory. Studies the later sections of Noor-ul-Anwar along with Husami, Taozi, and Talwe to explore advanced principles, abrogation (Naskh), speculative vs. definitive texts, contemporary legal issues, and juristic reasoning in complex scenarios. Focus on analytical thinking, case studies, research exercises, and application of fiqh principles to modern situations.',
    learning_outcomes: 'Master advanced Islamic jurisprudence principles · Analyze and evaluate differing juristic opinions · Conduct research in classical and contemporary fiqh · Apply Usool Fiqh methodology to modern legal and ethical issues',
    main_books: 'Noor-ul-Anwar (Qiyas to end), Husami, Taozi, Talwe',
    schedule: '3-4 days/week · 60-90 min per session',
    sort_order: 17
  },

  // Sarf & Nahw Courses (3)
  {
    title: 'Basic Sarf & Nahw Course',
    category: 'Sarf',
    level: 'Beginner',
    duration: '6 Months',
    fee_usd: '$20-$30',
    fee_pkr: '~PKR 5,500-8,500',
    prerequisites: 'None',
    description: 'For students starting Arabic grammar and morphology from scratch. Covers Arabic letters, vowels (Harakat), simple nouns and verbs (singular, dual, plural), basic sentence structures (subject, predicate, object), and practical exercises using Quranic verses. Includes recitation practice (Ijra) to improve fluency and pronunciation. Emphasizes understanding and applying basic grammatical rules in reading and writing Arabic.',
    learning_outcomes: 'Read and understand basic Arabic sentences · Recognize and conjugate simple nouns and verbs · Apply fundamental grammatical rules in Quranic reading · Prepare for Intermediate Sarf & Nahw',
    main_books: 'Irshad-us-Sarf, Nahw-e-Meer with Ijra',
    schedule: '3-5 days/week · 45-60 min per session',
    sort_order: 18
  },
  {
    title: 'Intermediate Sarf & Nahw Course',
    category: 'Sarf',
    level: 'Intermediate',
    duration: '10 Months',
    fee_usd: '$25-$35',
    fee_pkr: '~PKR 7,000-10,000',
    prerequisites: 'Basic Sarf & Nahw',
    description: 'Provides deeper understanding of Arabic morphology and sentence structures. Covers detailed verb forms (past, present, imperative) and derivatives, complex noun forms and pluralization, grammatical cases (Marfu\', Mansub, Majrur), sentence analysis (prepositions, pronouns, conjunctions), and application of rules to Quranic verses and classical Arabic texts. Emphasizes reading comprehension and analytical skills.',
    learning_outcomes: 'Analyze and construct complex Arabic sentences · Conjugate verbs and nouns accurately · Apply grammar rules to Quranic and classical Arabic texts · Prepare for Advanced Sarf & Nahw',
    main_books: 'Ilm-us-Sigha, Al-Kafia',
    schedule: '3-4 days/week · 60 min per session',
    sort_order: 19
  },
  {
    title: 'Advanced Sarf & Nahw Course',
    category: 'Sarf',
    level: 'Advanced',
    duration: '8 Months',
    fee_usd: '$35-$50',
    fee_pkr: '~PKR 10,000-15,000',
    prerequisites: 'Intermediate Sarf & Nahw',
    description: 'For students aiming for mastery in Arabic grammar and morphology. Using Sharah al-Jami, covers advanced verb forms and derivatives, irregular verbs, complex sentence structures (conditional, negation, emphasis), advanced noun forms and exceptions, syntax analysis of Quranic verses and Hadith, and application of grammar in advanced writing, Tafseer, and scholarly interpretation.',
    learning_outcomes: 'Master complex Arabic grammar and sentence structures · Analyze classical and Quranic texts accurately · Prepare for advanced Islamic studies in Tafseer, Hadith, and Fiqh',
    main_books: 'Sharah al-Jami',
    schedule: '3-4 days/week · 60-90 min per session',
    sort_order: 20
  },

  // Hadith Courses (4)
  {
    title: 'Basic Hadith Course',
    category: 'Hadith',
    level: 'Beginner',
    duration: '4 Months',
    fee_usd: '$20-$30',
    fee_pkr: '~PKR 5,500-8,500',
    prerequisites: 'None',
    description: 'Introduces students to the sayings, actions, and approvals of Prophet Muhammad (PBUH). Covers fundamentals of Hadith sciences (Ilm al-Hadith), basic classification of Hadith (Sahih, Hasan, Da\'if), selected Hadiths on daily life, morals, and worship, and correct reading and basic Arabic understanding for Hadith. Focuses on practical application and understanding how Hadith guides daily conduct and spiritual life.',
    learning_outcomes: 'Understand basic Hadith classifications and importance · Memorize and explain selected Hadiths · Apply basic Hadith teachings to daily life · Prepare for Intermediate Hadith studies',
    main_books: 'Riyadh-us-Saliheen (selected sections) / Basic Hadith Notes',
    schedule: '3-5 days/week · 45 min per session',
    sort_order: 21
  },
  {
    title: 'Intermediate Hadith Course',
    category: 'Hadith',
    level: 'Intermediate',
    duration: '6 Months',
    fee_usd: '$25-$35',
    fee_pkr: '~PKR 7,000-10,000',
    prerequisites: 'Basic Hadith Course',
    description: 'Provides deeper understanding of Hadith with contextual analysis. Covers detailed Hadith collections (meanings and context), the chain of narrators (Isnad) and Hadith terminology, practical application in daily life, and comparison and analysis of Hadiths to resolve apparent contradictions. Bridges memorization and analytical understanding.',
    learning_outcomes: 'Analyze Hadith texts with context and reasoning · Identify authentic Hadiths · Apply Hadith teachings to contemporary situations · Prepare for Advanced Hadith studies',
    main_books: 'Mishkat al-Masabih / Selected Hadith Collections',
    schedule: '3-4 days/week · 60 min per session',
    sort_order: 22
  },
  {
    title: 'Advanced Hadith Course',
    category: 'Hadith',
    level: 'Advanced',
    duration: '2 Years',
    fee_usd: '$35-$50',
    fee_pkr: '~PKR 10,000-15,000',
    prerequisites: 'Intermediate Hadith Course',
    description: 'For students aiming for mastery in Hadith studies. In-depth analysis of Sahih al-Bukhari, Sahih Muslim, and other major collections; detailed study of Isnad and Matn; advanced authentication methods (Ilm al-Rijal, Ilm al-Jarh wa al-Ta\'dil); application of Hadith in Fiqh, Tafseer, and contemporary Islamic issues; and Sharah (explanation) of complex Hadiths and scholarly interpretations.',
    learning_outcomes: 'Master major Hadith collections and their explanations · Authenticate and critically analyze Hadith using classical methods · Apply Hadith knowledge to Fiqh, Tafseer, and modern issues · Prepare for teaching, research, or scholarly work in Hadith sciences',
    main_books: 'Sahih al-Bukhari, Sahih Muslim, Sharah of Major Hadith Collections',
    schedule: '3-4 days/week · 60-90 min per session',
    sort_order: 23
  },
  {
    title: 'Takhassus fil Hadith (Specialization in Hadith Sciences)',
    category: 'Hadith',
    level: 'Specialized',
    duration: '2 Years',
    fee_usd: '$50-$70',
    fee_pkr: '~PKR 15,000-22,000',
    prerequisites: 'Basic → Intermediate → Advanced Hadith completion (all three levels)',
    description: 'The highest level of Hadith education — an advanced specialization for students who have completed all three Hadith levels and want to master Hadith sciences. Focuses on in-depth study of all six major Hadith collections, advanced Sharah of complex Hadiths, detailed Isnad and Matn analysis, advanced authentication methodologies, resolving contradictions and understanding narration variations, application to Fiqh and Tafseer, and guidance on teaching, scholarly writing, and issuing fatawa.',
    learning_outcomes: 'Master classical Hadith texts and commentaries · Analyze chains of narrators and authenticate narrations accurately · Interpret complex Hadiths and resolve scholarly differences · Conduct research, write scholarly articles, and teach Hadith at an advanced level',
    main_books: 'Sahih al-Bukhari, Sahih Muslim, Sunan Abu Dawood, Tirmidhi, Nasa\'i, Ibn Majah, Musnad Collections, Classical Commentaries',
    schedule: '3-5 days/week · 90 min per session',
    sort_order: 24
  }
];

module.exports = courses;
